# Generated by Django 4.1.3 on 2022-11-05 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('firm', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=6)),
                ('occupation', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('equity_type', models.CharField(max_length=125)),
                ('transaction_type', models.CharField(max_length=125)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.user')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=125)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
            ],
        ),
    ]
