# Generated by Django 4.1.3 on 2022-11-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0003_alter_agent_id_alter_miscproduct_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiscProduct',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
    ]
