# Generated by Django 4.1.3 on 2022-11-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0006_alter_agent_fee_alter_property_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
