# Generated by Django 4.1.3 on 2022-11-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0008_alter_agent_table_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiscProduct',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
