# Generated by Django 4.1.3 on 2022-11-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0012_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
