# Generated by Django 4.1.3 on 2022-11-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0017_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
