# Generated by Django 4.1.3 on 2022-11-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0019_alter_property_options_alter_agent_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertransaction',
            options={'verbose_name': 'user transaction'},
        ),
    ]
