# Generated by Django 4.1.3 on 2022-11-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0021_alter_usertransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=125)),
            ],
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.transactiontypes'),
        ),
    ]
