# Generated by Django 4.1.3 on 2022-11-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0027_alter_agent_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
