# Generated by Django 4.1.3 on 2022-11-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0041_alter_agent_options_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertransaction',
            name='agent',
        ),
        migrations.AddField(
            model_name='miscproduct',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent'),
        ),
        migrations.AlterModelTable(
            name='agent',
            table='financial_system_agent',
        ),
        migrations.AlterModelTable(
            name='user',
            table='financial_system_user',
        ),
    ]
