# Generated by Django 4.1.3 on 2022-11-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0051_alter_agent_options_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStocksOnDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'List Stocks On Date',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='agent',
            table='financial_system_agent',
        ),
        migrations.AlterModelTable(
            name='user',
            table='financial_system_user',
        ),
        migrations.CreateModel(
            name='ListUserTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.transactiontypes')),
            ],
            options={
                'verbose_name': 'List User Transaction',
            },
        ),
    ]
