# Generated by Django 4.1.3 on 2022-11-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0054_remove_stocktransaction_agent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListStocksOnDate',
        ),
        migrations.RemoveField(
            model_name='miscproduct',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='othertransaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='othertransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='othertransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='propertytransaction',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='propertytransaction',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertytransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='propertytransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='ListUserTransactions',
        ),
        migrations.DeleteModel(
            name='MiscProduct',
        ),
        migrations.DeleteModel(
            name='OtherTransaction',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyTransaction',
        ),
        migrations.DeleteModel(
            name='TransactionTypes',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
