# Generated by Django 4.1.3 on 2022-11-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_system', '0063_delete_bond_remove_othertransaction_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('firm', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issuer', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=125)),
                ('bond_yield', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MiscProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('product_type', models.CharField(max_length=125)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=125)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'Transaction Type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=6)),
                ('occupation', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shares', models.IntegerField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.stock')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.transactiontypes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.user')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.property')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.transactiontypes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.user')),
            ],
            options={
                'verbose_name': 'Property Transaction',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.user'),
        ),
        migrations.CreateModel(
            name='OtherTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.miscproduct')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.transactiontypes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_system.user')),
            ],
            options={
                'verbose_name': 'Other Product Transaction',
            },
        ),
    ]
