# Generated by Django 4.1.3 on 2022-11-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0065_alter_agent_options_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.AlterModelTable(
            name='agent',
            table='financial_system_agent',
        ),
        migrations.AlterModelTable(
            name='user',
            table='financial_system_user',
        ),
    ]
