# Generated by Django 4.1.3 on 2022-11-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0066_bank_alter_agent_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.bank'),
        ),
    ]
