# Generated by Django 4.1.3 on 2022-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_system', '0068_alter_miscproduct_options_userexpenditures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_system.stock')),
            ],
        ),
    ]
