# Generated by Django 4.1.3 on 2022-11-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfileupload',
            options={'verbose_name': 'File Upload'},
        ),
    ]
